we_crea:
    resource: "@WeCreaBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"


